SlimeVR/SlimeVR-Tracker-ESP

src/configuration.cpp
=> Update configuration to initialize the config if none is found in memory

src/main.cpp
https://www.desmos.com/calculator/hnuztemjwd
=> Update default battery level estimation

lib/mpu6050/MPU6050.cpp
A tiny bit faster and seems to be more stable (at least shouldn't block execution with waiting for the next packet if this happens). Tested on esp8266 with mpu9250.
=> Improve DMP FIFO packet reader

platformio.ini
Causes issues with ESP32, needs additional testing.
=> Revert -O2 optimization

src/batterymonitor.cpp, src/batterymonitor.h, src/consts.h, src/defines.h, src/main.cpp
Re-enable MCP+internal battery measurement
Fixed typo
Clear console of rubbish when resetting esp
Force disable leds on ESP01 (until Serial logging has been revised maybe)
=> Small changes for testing

src/consts.h, src/debug.h, src/main.cpp, src/wifihandler.cpp
Added Power saving options for an average saving of *6mA* on minimum settings => **AP dependent!**
**None:** compatibility mode, disables all saving and works like before
**Minimum:** new recommended mode, saves about 6mA on my setup
**Moderate:** Tracker could miss some broadcasts, tests were successful but needs more testing, would save a bit more
**Maximum:** will need code changes in the rest of the code => disconnects otherwise, will check this again in the future
(maximum is disabled for now)
=> Added Power saving options

src/debug.h
Hotfix for POWER_SAVING_NONE not actually having intended effect (still sleeping unlike old config)
Sorry i forgot this :(
=> Hotfix for POWER_SAVING_NONE

platformio.ini
My test with ESP32 and MPU-6050 didn't show any problems and the caused issue seems to be unrelated to this change.
https://discord.com/channels/817184208525983775/818062281636053012/922144740013649950
So let's try again maybe or conduct more tests?🤔
=> Re-enable -O2 flag

src/network/udpclient.cpp
Can't tell if this was kept as a joke or not - it is kind of funny.
=> "handshale" -> "handshake"

src/main.cpp
=> Fix RSSI report timing

src/sensors/bmi160sensor.cpp
1. Rate limiter is no longer required and reduces TPS even more with new power saving options.
2. Switch to LEDManager.
=> Update BMI160 code

src/network/udpclient.cpp
Check if the server is connected before sending some packages.
Little bugfix on line 338
=> Connected Check

src/debug.h, src/sensors/icm20948sensor.cpp, src/sensors/icm20948sensor.h, src/sensors/sensorfactory.cpp
Thanks to all the testers and help
=> ICM20984 patch and cleanup

lib/ota/ota.cpp, src/network/udpclient.cpp, src/network/wifihandler.cpp, src/serial/serialcommands.cpp
Add some minor line change to the serial log.
It improves readability.
=> Clean up Serial log

src/serial/serialcommands.cpp
Not the cleanest solution, but it works for now.
We need a equivalent method for this on the ESP32s.
=> Fix compilation for ESP32

.github/workflows/actions.yml, .gitignore, ci/build.py
Added a pipeline which builds for ESP8266 and ESP32 on every push and pull_request. This pipeline also uploads the compiled .bin firmware file to Github Artifacts.
There you go @adigyran and @Eirenliel ^^
=> Add CI pipeline

lib/mpu9250/MPU9250.cpp
Some MPU9250 with magnetometer not reading works fine.
=> MPU9250: Communicated magnetometer as I2C Slave 

src/batterymonitor.cpp, src/batterymonitor.h, src/debug.h, src/ledmgr.cpp, src/ledmgr.h, src/logging/Level.cpp, src/logging/Level.h, src/logging/Logger.cpp, src/logging/Logger.h, src/main.cpp, src/network/udpclient.cpp, src/network/wifihandler.cpp, src/network/wifiprovisioning.cpp, src/sensors/bmi160sensor.cpp, src/sensors/bmi160sensor.h, src/sensors/bno055sensor.cpp, src/sensors/bno055sensor.h, src/sensors/bno080sensor.cpp, src/sensors/bno080sensor.h, src/sensors/icm20948sensor.cpp, src/sensors/icm20948sensor.h, src/sensors/mpu6050sensor.cpp, src/sensors/mpu6050sensor.h, src/sensors/mpu9250sensor.cpp, src/sensors/mpu9250sensor.h, src/sensors/sensor.cpp, src/sensors/sensor.h, src/serial/serialcommands.cpp, src/utils.h
I still need to figure out how to use PROGMEM strings for logging, but I will do that in a later PR ^^
Thank you for contributing, @unlogisch04 :)
=> Implement new logger

src/sensors/bmi160sensor.cpp, src/sensors/mpu9250sensor.cpp
=> Remove newlines from logging in calibration

ci/build.py, ci/devices.json, ci/platformio.ini
With this, we're now doing 2x8 (ESP8266 / ESP32 + the different IMUs) matrix builds, resulting in 16 builds.
Maybe we can split these up into parallel builds?
=> Improve CI

src/debug.h, src/network/packets.h, src/network/udpclient.cpp, src/sensors/bmi160sensor.cpp, src/sensors/bno055sensor.cpp, src/sensors/bno080sensor.cpp, src/sensors/icm20948sensor.cpp, src/sensors/mpu6050sensor.cpp, src/sensors/mpu9250sensor.cpp, src/utils.h
Introduces:
- a new debug flag `ENABLE_INSPECTION`
- a new packet type (105, 0x69)
- loads of sent packets when `ENABLE_INSPECTION` is true :P
This packet type is used to implement a [simple data capturing agent](https://github.com/TheDevMinerTV/SlimeVR-Tracker-Inspector).
=> Implement the inspection packet

src/status/StatusManager.cpp
Forgot to flip around some log statements and actually check that the status wasn't already set before setting in against / logging it.
=> Fixup StatusManager

ci/build.py, platformio.ini, src/GlobalVars.h, src/configuration/CalibrationConfig.cpp, src/configuration/CalibrationConfig.h, src/configuration/Configuration.cpp, src/configuration/Configuration.h, src/configuration/DeviceConfig.h, src/consts.h, src/main.cpp, src/network/udpclient.h, src/sensors/bmi160sensor.cpp, src/sensors/bmi160sensor.h, src/sensors/icm20948sensor.cpp, src/sensors/icm20948sensor.h, src/sensors/mpu6050sensor.cpp, src/sensors/mpu6050sensor.h, src/sensors/mpu9250sensor.cpp, src/sensors/mpu9250sensor.h, src/sensors/sensor.h, src/serial/serialcommands.cpp, src/utils.h, test/i2cscan.cpp
=> Rework configuration to use LittleFS

src/sensors/mpu9250sensor.cpp
Thank you TinyOra on Discord for pointing this out!
=> Fix MPU9250 compilation with Mahony / Madgwick enabled

src/network/udpclient.cpp
=> Fix UDPClient compiler warnings

src/serial/serialcommands.cpp
Adding ESP32 factory reset. 
Adding Warning if hard coded credential are used.
=> ESP32 Factory Reset

platformio-tools.ini
=> Remove backslash for esp01 and wroom32 boards

src/serial/serialcommands.cpp
Implement Serial Command ``GET CONFIG``
as mentionned in https://github.com/SlimeVR/SlimeVR-Tracker-ESP/issues/6
=> Add GET CONFIG serial command

src/network/wifihandler.cpp
If the WiFi was not connected in a certain time, the message was was spammed.
=> Update wifihandler.cpp spamming serial console

lib/i2cdev/I2Cdev.cpp
https://github.com/jrowberg/i2cdevlib/issues/670
https://github.com/espressif/arduino-esp32/issues/6674
https://github.com/espressif/arduino-esp32/issues/6674#issuecomment-1122606853
=> fixing error on ESP32 using BMI160

src/configuration/Configuration.cpp
=> Unable to save AUX IMU calibration data when using MPU9250*2

src/debug.h, src/network/udpclient.cpp, src/sensors/bmi160sensor.cpp, src/sensors/bno055sensor.cpp, src/sensors/bno080sensor.cpp, src/sensors/icm20948sensor.cpp, src/sensors/icm20948sensor.h, src/sensors/mpu6050sensor.cpp, src/sensors/mpu6050sensor.h, src/sensors/mpu9250sensor.cpp, src/sensors/mpu9250sensor.h, src/sensors/sensor.cpp, src/sensors/sensor.h, src/serial/serialcommands.cpp
This PR adds support for sending acceleration data to the server for the BNO085 and MPU6050 chips.
=> Send acceleration data

platformio.ini, src/network/wifihandler.cpp, src/network/wifihandler.h
I wanted to use a static IP address to manage my trackers.
=> Add support for setting the static IP address

src/network/wifihandler.cpp
For some reason, #195 was merged even though it caused C.I. to fail.
This PR should fix compilation for people who don't use static IPs.
=> Fix compiliation error for users that don't use static IPs.

src/sensors/bmi160sensor.cpp, src/sensors/icm20948sensor.cpp, src/sensors/icm20948sensor.h
Fix Issue #198 
Waiting for confirmation.
=> Icm20948 magnetometer fix

.github/workflows/release.yml
Automaticaly create a release a draft release with the current artifacts when you create a tag
=> Release workflow test

src/GlobalVars.h, src/debug.h, src/defines.h, src/sensors/sensor.h, src/serial/serialcommands.cpp
Added command for testing, also GET INFO now should display information on sensors
=> Added GET TEST command

src/sensors/mpu9250sensor.cpp
fixing another screw-up of mine, this one was spotted by @unlogisch04 (thank you!)
links to portions of diffs showing the accidental changes:
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/commit/65df578bfcd4129a68f23f0c7928128aff40d4a4#diff-15dd1929434813eba418648cae1b4c836aa7d505ecf4fae91492d69a2cd2192cR263
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/commit/65df578bfcd4129a68f23f0c7928128aff40d4a4#diff-15dd1929434813eba418648cae1b4c836aa7d505ecf4fae91492d69a2cd2192cR338
~~I'm going to fully check #200 in case there are other component swaps that were accidentally made.~~ yeah it only touches bmi for the accelerometer and there isn't any fancy swapping going on there.
=> mpu9250: fix magnetometer component issue introduced with #200

src/sensors/icm20948sensor.cpp
=> Fix building with magnetometer enabled

src/consts.h
Adds Haritora/SlimeTora constants to firmware and fixes "unknown" being misspelled
=> Add Haritora to consts

src/sensors/softfusion/drivers/icm45base.h
Seems like the "Don't copy memory on ICM45 reads" commit causes reproducible and constant crashes on ESP32-C3. SInce it's a fairly small performance improvement, I'm simply reverting it to fix the issue.
=> Revert "Don't copy memory on ICM45 reads"

src/sensors/SensorManager.h, src/sensors/sensoraddress.h
See https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/398 for what this branch fixes.
=> Swapped imu addr fix

src/debug.h
=> fix i2c clockspeed to default 400khz back

src/consts.h
complements https://github.com/SlimeVR/SlimeVR-Server/pull/997
=> Add Gestures Boards

lib/ota/ota.cpp, src/debug.h
=> Remove OTA timeout

src/sensorinterface/i2cimpl.h, src/sensors/SensorBuilder.h
- Fix pointer issue (build)
- Fix null reference to string issue (int 255)
- Recreate hex output for IMU address
=> Fix build and runtime crash

platformio-tools.ini, platformio.ini, src/debug.h, src/globals.h, src/main.cpp, src/network/connection.cpp, src/serial/serialcommands.cpp
Embed vendor information into build parameters & defines so SlimeVR vendors can maintain their own firmware updates without adding new boards
Bump protocol version to 21
=> Send vendor information on handshake
