SlimeVR/SlimeVR-Tracker-ESP

src/consts.h

it was BNO6050 instead of MPU6500

fixed the typo in consts.h

---

lib/bno080/BNO080.cpp
lib/bno080/BNO080.h
lib/math/quat.cpp
lib/math/quat.h
lib/math/vector3.h
src/bno080sensor.cpp
src/defines.h
src/main.cpp
src/sensor.h
src/udpclient.cpp
src/udpclient.h

Code and protocol refactoring
* Replace doubles with floats in math: double precision is not used in sensor readings, we can save CPU cycles and memory, and able to use more things without casting
* BNO now sends data to the server with new PACKET_ROTATION_DATA that supports different data types, data accuracy information, and more than 2 sensors
* BNO now can use magnetometer if flag is set, or can separately send magnetometer data as DATA_CORRECTION that server can use however it wishes
* BNO now sends tap data (it's not used by server and seem to be very unreliable, 95% of taps are ignored by it (need higher report rate?))
* Fixed handshake

Protocol refactoring

---

src/defines.h

Using common I2C pins for ESP32 to prevent lockup when using MPU
Pin 12 cause boot to fail when pull to HIGH (which it does on mpu6050)
Source: https://randomnerdtutorials.com/esp32-pinout-reference-gpios
Pinout: https://lastminuteengineers.com/esp32-arduino-ide-tutorial/#esp32-development-board-pinout

Using common I2C pins for ESP32 to prevent lockup

---

src/serialcommands.cpp

Exception (28) occurs on ESP8266 when no arguments are given to the serial command 'SET'.

Handling exceptions when SET has no args

---

src/consts.h
src/defines.h

1. Added support for Wemos D1 Mini board and Wemos D1 Battery shield
2. Fixed batteryADCMultiplier calculation to be more accurate on voltage value

Wemos D1 Mini support and batteryADCMultiplier fix

---

src/defines.h
src/main.cpp
src/mpu6050sensor.cpp
src/sensor.h

This pull request adds support for using two MPU-6050's connected to one device.
This mode is more subject to interference than running in single MPU mode. Good solder joints, cables and a good Wi-Fi connection is needed to keep the TPS high. I can run 4 normal trackers, and one with dual on my Wi-Fi with minimal issues, but adding more dual trackers unfortunately makes my router sad.
Any future documentation for this mode should explain these issues (I will simply create a discord post for now). If the user has problems with TPS they should try to unplug the second tracker and run it in single MPU mode.

Support for dual MPU-6050's

---

src/consts.h
src/defines.h

Provide pre-defined values to reduce possible mistakes caused by user input. The change is backward compatible with custom values and names of defines assume clockwise rotation.
Rationale:
1. There were several issues caused by accidental division by zero, modification of wrong values and etc.
2. Such values are easier to invert with `-` in case IMU is facing towards the user and also allows to invert sign of zero value.

Provide pre-defined rotation values

---

src/defines.h

People tested and found that 400khz is more stable for MPUs also

Make 400khz speed default for MPU sensors 

---

src/mpu6050sensor.cpp

Since the IMU_MPU6050_RUNTIME_CALIBRATION is checked before sensor.h is included (and thus before defines.h/debug.h) it is in fact at that point not set yet.
So basically the old MotionApps20 is always included. If we move defines.h before motionapps that should be fixed.

MPU6050 MotionApps bugfix

---

platformio.ini

With -O2 optimization, the speed increases by 30% while RAM usage increased by 0.2% and FLASH usage - by 1.1% on esp8266 (IMU_MPU6050). Might be a subject to additional testing, but no bugs were noticed.
With `-Os`:
```
RAM:   [====      ]  44.6% (used 36504 bytes from 81920 bytes)
Flash: [===       ]  33.8% (used 352907 bytes from 1044464 bytes)
```
Loop execution times
Min: 241uS
Max: 1870uS
Average: 329uS
With `-O2`:
```
RAM:   [====      ]  44.8% (used 36720 bytes from 81920 bytes)
Flash: [===       ]  34.9% (used 364271 bytes from 1044464 bytes)
```
Loop execution times
Min: 162uS
Max: 1430uS
Average: 242uS

Enable -O2 optimization option

---

src/sensorfactory.cpp
src/sensorfactory.h

Small bugfix to fix the code crashing when no primary IMU is found. Using this method, a secondary IMU might still be found. Alternatively the return value of `sensors.create()` needs to be checked, raising an error and halting execution if it failed.

Fix crash when primary IMU isn't found

---

src/wifihandler.cpp

When SmartConfig is launched, wifi station switches to idle state and overwrites previous wifi state, so we always get status 0 instead of actual error.

Fix failed wifi connection status

---

src/consts.h
src/network/wifihandler.cpp

I could have sworn i made a PR for this but i must have forgotten to push the create button, my bad... :c
Might want to test the actual esp32 power saving still on actual trackers => i only have the chips but no imus anymore to hook up.
In any (worst) case if esp32 ps doesn't work you can enable POWER_SAVING_LEGACY now which will literally go back to the state before any power saving edits were even a thing... so then they can at least work again pretty quickly without having to use different code...

Hotfix for esp32 not compiling

---

src/globals.h

Including Arduino.h for getting all definitions from Boards before we go trough all other definitions. (Pins Definition)

Fixing buildings error with WEMOS board

---

src/sensors/bmi160sensor.cpp

1. Add "flip to calibrate" code from MPU9250 to make it possible to calibrate.
2. Accelerometer is already being normalized in Mahony filter function, so not needed on scaling stage.

Add "flip to calibrate" and remove unnecessary accelerometer normalization

---

lib/mpu6050/MPU6050.cpp
lib/mpu9250/MPU9250.cpp
src/sensors/mpu6050sensor.cpp
src/sensors/mpu9250sensor.cpp

Allow only MPU92xx for MPU9250 library, and any MPU for MPU6050 library. Also fixes broken device ID check for MPU92xx family.

Use strict device ID check for MPUs

---

lib/magneto/mahony.cpp
lib/math/helper_3dmath.cpp

1. Unify feedback term variables and integral feedback computation
2. Use the same variable naming for both functions and code style.
3. Pre-multiply `deltat` once then apply gyro factors in function with magnetometer.
4. Use inverse square root function with a bit better precision (from the same source in comments).

Refactor mahony functions

---

src/serial/serialcommands.cpp

Erase the EEPROM and credentials for use when using the ESP for selling or other purposes.
(I fixed the EEPROM size to 4096 bytes, but as far as I know, there was no other size.If a change is required, it may need to be modified.)

cmdFactoryReset function implementation

---

src/serial/serialcommands.cpp

It's seems like a typo.
(It was so similar that I didn't know what was wrong...!)

cmdReport -> cmdReboot

---

lib/magneto/magneto1.4.cpp
src/sensors/bmi160sensor.cpp
src/sensors/mpu9250sensor.cpp

Current magneto implementation heavily relies on stack memory allocation of `double` arrays. This results in crash on esp8266 due to insufficient RAM. This PR combines heap allocation and stack allocation to keep calculation speed and save a lot of RAM.

Magneto memory optimization

---

platformio.ini

Silly little commit that just adds a comment about the importance of the spaces in front of the wifi build flags. Feel free to modify the wording if it is still not clear enough.

Small addition to comments for platformio file

---

src/logging/Logger.cpp
src/logging/Logger.h
src/sensors/sensor.cpp

The logger now shows the IMU ID on the tracker in log statements:

Implement better IMU identification in logger

---

src/network/packets.h
src/network/udpclient.cpp
src/sensors/bmi160sensor.cpp
src/sensors/bno055sensor.cpp
src/sensors/bno080sensor.cpp
src/sensors/icm20948sensor.cpp
src/sensors/mpu6050sensor.cpp
src/sensors/mpu9250sensor.cpp

- Fixed BNO08x not sending inspection packets when `useMagnetometerAllTheTime || !useMagnetometerCorrection` is `true`
- Renamed inspection packet sending related to clearly indicated that they're meant for the inspection subprotocol
- Introduced calibration packet type for inspection

Inspection packet improvements

---

src/debug.h

Discovered today that using POWER_SAVING_MINIMUM causes pauses in data transmission every second or two on BNOs. Using POWER_SAVING_LEGACY fixes the problem.
From discord: https://discord.com/channels/817184208525983775/878727840118505533/952135552323444757

Fix sporadic data pauses from POWER_SAVING_MINIMUM

---

src/batterymonitor.h

Corrected values for battery sense, really should be moved to defines.h since these are likely board dependent.

Fix battery sense values

---

src/sensors/mpu9250sensor.cpp

The MPU9250's magnetometer correction seems to be quite aggressive and creates heavy orientation jitter.
Lowering it to ``0.02``  reduces the jitter and also corrects itself fast enough for fast movements.
The value probably can be set lower tbh.
Orientation quality seems to be equal with ICM20948 with this change.
**Correction with 0.2:**
https://user-images.githubusercontent.com/22834512/163219863-1ad64f75-1d44-41eb-87dd-0c5f7cac869f.mp4
**Correction with 0.02:**
https://user-images.githubusercontent.com/22834512/163221958-8f3071e8-cf10-42e8-a2c5-67b3d6451cf9.mp4

[MPU9250] Fix too aggressive magnetometer correction

---

src/consts.h
src/debug.h
src/defines.h
src/globals.h

the LED_PIN is wrong in const.h
moved it to globals.h with the option to accept changes from defines.h
with that it should fix #37 
my understanding is, that globals.h adds all the missing stuff from defines.h with the default values.
Any meaning on this?

Move LED define to global + defines to fix TTGO compile

---

ci/build.py
ci/devices.json
platformio.ini
src/defines.h
src/globals.h

Instead of using LED_BUILTIN as a value in defines.h
we can leave LED_PIN undefined. In that case global.h 
will look if LED_BUILTIN is defined or not.

Fixing compile Error if LED_BUILTIN is not defined

---

lib/mpu6050/MPU6050.cpp

some MPU-6500 seem to have their ID as 0x74.
This commit adds 0x74 as an legal deviceID for the MPU6050 library

Fix MPU-6500 cannot connect

---

platformio.ini

fix a warning, and enable the function for echo again

fix warning in new platformio

---

src/sensors/SensorManager.cpp

Handling exceptions that occur when using MPU-6050 with BNOs. It looks like a little bit of a typo.

fix #185 (6050 does not work when the first IMU is BNO085 and the second IMU is 6050)

---

src/sensors/mpu6050sensor.cpp

Fixed to show real sensors (like MPU-6500) instead of always 'MPU-6050' when using MPU 6 series sensors.

Fixed sensor names to be more clear

---

src/main.cpp

For still unknown reasons BNO055 and ICM20948 (and may probably others) have I2C-Scan issues when starting up or resetting. Without this fix, I2C-Scan has a random chance of not finding those IMUs. It either fails to find them or deadlocks the ESP.
Example error:
```
[INFO ] [SlimeVR] SlimeVR v0.2.3 starting up...
[INFO ] [Configuration] Found up-to-date configuration v1
[DEBUG] [Configuration] Found sensor calibration for ICM20948 at index 0
[INFO ] [Configuration] Loaded configuration
[ERR] I2C: Can't find I2C device on provided addresses, scanning for all I2C devices and returning 
[DBG] I2C (@ D2(4) : D1(5)): I2C device found at address 0x28  ! 
[ERROR] [ErroneousSensor:0] IMU of type BNO055 failed to initialize 
[INFO ] [BNO055Sensor:1] Connected to BNO055 at address 0x28
```

Fix for I2C startup issues on BNO055 and ICM20948

---

src/network/wifihandler.cpp
src/network/wifihandler.h

I ran into this issue myself, and when people said that setting the device into 11G mode worked, I didn't see a reason to not use that as a workaround while the root issue is found! (Since I do not have this issue with other ESP32/8266 devices in my home on the same router.)
It does take longer compared to connecting via 11N as it waits for that connection to fail first, but it seems reliable for my network!
Workaround for issue: #203

Workaround for connecting to some ASUS+? routers

---

src/sensors/mpu9250sensor.cpp
src/sensors/mpu9250sensor.h

Idea is that using the FIFO with give us more accurate information, if we're able to process all of the samples.
One thing that should be done is a way to signal visibly somewhere that the buffer has overrun, so that we can realize that that's actually happening when testing this.
I'm going to leave a review highlighting all the TODOs I left in the code, so that other people can remark, and decide if they need to be handled now or later.

Make MPU9250 use the FIFO

---

src/debug.h
src/main.cpp
src/network/wifihandler.cpp
src/network/wifihandler.h
src/sensors/bno080sensor.cpp
src/sensors/mpu6050sensor.cpp
src/sensors/sensor.h
src/serial/serialcommands.cpp
src/serial/serialcommands.h
src/status/StatusManager.cpp
src/status/StatusManager.h

Fixes #6 and #215
Adds some minor fixes to logging for testing and debugging purposes.

Multiple debugging updates to serial interface

---

src/sensors/mpu9250sensor.cpp

This restores the swap from before #192, which I previously missed during that PR.
This may help with #218.

mpu9250: Swap the first two components of mag readings

---

src/batterymonitor.h
src/defines.h

This commit properly "fixes" the battery sense, in the previous fix I submitted (#139) I simply swapped the R1 and R2 values not noticing that the formula itself was wrong, not the default values. 
This rectifies that mistake by swapping the values again and fixing the formula instead. Now it should be consistent with the comments and the actual values inside the datasheet again and should cause less confusion.
This fix is OPTIONAL as it does not change anything relating to the behavior and only tries to improve code readability and consistency.

Proper battery sense fix

---

src/network/wifihandler.cpp

Firmware gets stuck in G mode - when the AP is N-only, it never reconnects.

wifi: Make reconnecting work again for N-only networks

---

lib/bmi160/BMI160.cpp

When testing my AIO tracker, I found that the whole batch of BMI160 all have 0xD3 as CHIP_ID instead of 0xD1, with all functionalities checked out ok after skipping the CHIP_ID check in testConnection().
I found this header containing three different CHIP_IDs:
0xD0 for 'BMI' (probably for engineering samples)
0xD1 for 'BMI_C2' (Matches the value listed in the datasheet)
0xD3 for 'BMI_C3' (probably for newer revisions of the chip).
https://github.com/BST-Github-Admin/drivers/blob/master/drivers/iio/imu/bmi160/bmi160_core.h
Considering 'BMI_C3' may get more usage if it's really a newer revision of the chip, add support for CHIP_ID value 0xD3 in case anyone gets their hands on some new chips as I do.

Add support for new variants of BMI160.

---

src/network/connection.cpp

Allow updating server feature flags in case we want to make them toggleable in future.

Allow more than 1 server flags packet per connection

---

lib/i2cscan/i2cscan.cpp
lib/i2cscan/i2cscan.h
src/batterymonitor.cpp
src/configuration/Configuration.cpp
src/configuration/Configuration.h
src/sensors/SensorManager.cpp
src/sensors/bmi160sensor.h
src/sensors/icm20948sensor.h
src/sensors/mpu6050sensor.h
src/sensors/mpu9250sensor.h

This PR contains my recent findings when enabling ESP32C3 board. With this changes the following issues are fixed:
- BMI160 shaky/not functional/completely drifty before calibration (because of uninitialized memory)
- BMI160 being broken after some amount of time, especially on rest ( may help with https://github.com/SlimeVR/SlimeVR-Tracker-ESP/issues/245 ) when temperature calibration is enabled (default).
- (Possibly) other sensors with calibration stored in tracker being broken before performing it.
- Trackers with AUX IMU compiled but not connected making server going crazy with OK/Error status changing every second (workaround for https://github.com/espressif/arduino-esp32/issues/8454 )

ESP32C3 stability improvements

---

lib/bno080/BNO080.cpp
lib/bno080/BNO080.h

So far firmware worked with assumption that it'll get 2 BNO reset responses, which is not always true.
In my testing it seems like first reset is performed automatically on BNO power on, then second is performed on demand by firmware.
When BNO was earlier in working order and firmware is restarting (because ESP crashed or was resetted without power cut) BNO will not generate first reset, which was assumed to happen in firmware so far. So BMI driver was waiting for 5 seconds starving software watchdog set to 3 seconds by default.
This change:
- makes firmware waiting only one second for first reset (to accelerate boot time when it's not happening)
- feeds watchdog during that waiting, just in case, so if will not crash even if we change timeout to 5 seconds again
- for ESP32 there is no …

BNO080: Try to handle reset better

---

src/sensors/SensorManager.cpp

Since #249 the firmware has a regression in sensor assignment logic and sets an `ErroneousSensor` instead of leaving an `EmptySensor` as is.
If there are multiple IMUs in defines (main + aux) and some of them are not connected (aux), it sends an `ErroneousSensor`.
Server logic for UDP tracker statuses also seems weird - it briefly shows an error, then gets overwritten with OK.
After the change in this PR the extra tracker no longer appears.
For reference old aux logic that used to scan all addresses:
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/blob/ed74944551cc7a635ce0ef2d2c66637a021a157b/src/sensors/SensorManager.cpp#L88-L97
Also logging below uses `sensorId+1` style of sensor numbering, so the new "not found" line uses the same. …

Fix sending ErroneousSensor if not found

---

src/network/connection.cpp
src/network/connection.h
src/sensors/SensorFusion.cpp
src/sensors/SensorFusion.h
src/sensors/SensorFusionDMP.cpp
src/sensors/SensorFusionDMP.h
src/sensors/bmi160sensor.cpp
src/sensors/bno055sensor.cpp
src/sensors/bno080sensor.cpp
src/sensors/icm20948sensor.cpp
src/sensors/mpu6050sensor.cpp
src/sensors/mpu9250sensor.cpp
src/sensors/sensor.cpp
src/sensors/sensor.h

Fixes #267 - acceleration updates are only sent with rotations again.
Refactored acceleration into a `Vector3`, reduced code duplication.
BNO08x was unaffected because it sets `newAcceleration` inside `if (imu.hasNewQuat())`.

Fix OPTIMIZE_UPDATES logic for acceleration

---

src/sensors/EmptySensor.h
src/sensors/SensorManager.cpp
src/sensors/sensor.cpp

This is changing default behavior of Sensors. If sensor failed to initialize (and has working=false) it will report error, not offline.
I added exception to Empty sensor, not to generate errors from disconnected (and not mandatory) aux imus.
I also made sensor manager set IMU_ERROR flag to statusManager. This way user will see 5 blinking leds on imu error. So far only bno sensor was setting that flag.

Report IMU errors

---

src/sensors/mpu9250sensor.cpp

Previous refactoring of the code rolled both the assignment of the temp variable and the calibration matrix multiplication into a single loop.
This causes issue because every iteration of the loop for the matrix multiplication uses every value of temp, and it is not completely initialized until the final loop iteration.
The solution is to split the loop into two.

Fix 9250 loop

---

src/sensors/SensorFusion.cpp

It wasn't passing all gyro samples to fusion if acceleration update rate is lower, resulting in broken rotation, also `magExist` condition was inverted.
Only useful for testing though.

Fix mahony/madgwick updates

---

lib/bmi160/BMI160.cpp
lib/bmi160/BMI160.h
src/sensors/bmi160sensor.cpp

- Removes bugged magnetometer error message;
- Fixes error masks starting with `0x` instead of `0b`;
- Pullups in mag initialization code are not needed.

BMI160: Fix magnetometer error check

---

src/sensors/SensorFusion.h
src/sensors/SensorFusionRestDetect.cpp
src/sensors/SensorFusionRestDetect.h

There's no define called [`SENSOR_WITH_REST_DETECT`](https://github.com/SlimeVR/SlimeVR-Tracker-ESP/blob/6d3299d3dcc30d6b5b49406fe6c29610f4892966/src/sensors/SensorFusionRestDetect.h#L9), samples were always processed twice for rest detection with VQF.

BMI160: Fix double rest detection

---

src/sensors/icm20948sensor.cpp

When on ESP8266 and ESP32-C3, it seems that the serial command "wifi set" holds up the loop for 1 sec. 
So i had to increase the timeout.

icm20948 timeout correction because of wifi set

---

platformio-tools.ini
src/consts.h
src/defines.h

This adds definition for ESP-WROOM-02
Tested against a board "WeMos D1 ESP Wroom 02"

Add BOARD_WEMOSWROOM02

---

README.md

This warning no longer seems to apply, as ESP32-C3 trackers with USB set to CDC mode work just fine when trying to set Wi-Fi credentials or access serial console in SlimeVR Server

Remove ESP32-C3 USB CDC warning

---

platformio.ini
src/network/connection.h

as @ButterscotchV requested, two flags to implicitly disable broadcast spamming the network. :)

feat: allow connecting to one specific server IP without broadcasting

---

src/sensors/icm20948sensor.cpp
src/sensors/icm20948sensor.h

The delay in sendData() makes at somepoint that the packetbundling does not work correctly. The ICM works without delay on ESP8266, ESP32-C3, ESP32-S2 Also added the LastData Flag for get info

Fix ICM20948 PacketBundling and LastData

---

src/motionprocessing/RestDetection.h
src/sensors/SensorFusion.cpp
src/sensors/SensorFusionRestDetect.cpp
src/sensors/SensorFusionRestDetect.h
src/sensors/bmi160sensor.cpp

Sensor fusion expects the time to be in seconds while rest detection expects it to be in microseconds. This makes is so when the update sensor fusion is called the rest detection now gets the time in micros. Also linear acceleration was missing parentheses giving wrong results (only lsm6dsv uses this to my knowledge)

Fix rest detection timescale

---

src/FSHelper.cpp
src/FSHelper.h
src/configuration/Configuration.cpp

This cleans up a bunch of duplicated code from the configuration class.

Move platform specific code for FS access into an abstraction

---

src/sensors/bmi160sensor.cpp
src/sensors/bno055sensor.cpp
src/sensors/bno080sensor.cpp
src/sensors/icm20948sensor.cpp
src/sensors/icm42688sensor.cpp
src/sensors/mpu6050sensor.cpp
src/sensors/mpu9250sensor.cpp
src/sensors/sensor.cpp
src/sensors/sensor.h

Previous codes have ambiguity in when to computing delta angle for update check: 
- either before applying `sensorOffset` (e.g. BMI160) 
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/blob/b744c536764559c71b3d062552d159511fe8b69a/src/sensors/bmi160sensor.cpp#L364-L370
- or after it (e.g. ICM42688).
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/blob/b744c536764559c71b3d062552d159511fe8b69a/src/sensors/icm42688sensor.cpp#L175-L179
This PR set the applying of `sensorOffset` to be a common behavior before computing delta angle and setting the ready flag, removing the duplicated code distributed in each sensor's class.
With this PR, the update to `fusedQuaternion` and `acceleration` are also limited to `setFusedRotation` and `setAcceleration` methods, which may simplify future modifications …

Merge code for applying `sensorOffset` and setting data ready flag

---

src/FSHelper.cpp

This is fixing ESP8266 calibration storage which seems to be broken since https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/319
Use open to check if it is a directory or not as on ESP32.
As requested in comments in https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/321

 fshelper: fixed ESP8266 regression caused by abstracting FS access #321

---

src/sensors/SensorFusion.h

`motionBiasEstEnabled` should be `true` if `VQF_NO_MOTION_BIAS_ESTIMATION` isn't defined

Fix enabling motion bias estimation

---

src/GlobalVars.h
src/batterymonitor.h
src/serial/serialcommands.cpp

This update modifies the `GET INFO` serial command to include battery voltage and battery level (displayed as a percentage).
This enhancement provides detailed battery status information in the serial output and was a big help when I was troubleshooting a connection issue with the battery sense wire.

GET.INFO Serial Command Should Returns Battery Voltage & Level (in Percentages)

---

.github/dependabot.yml
.github/workflows/actions.yml
.github/workflows/release.yml
ci/requirements.txt

GitHub Actions fails now because the versions are so old. This updates those and adds dependabot so it'll automatically update them. :3

Add dependabot & update workflows

---

.gitignore
platformio.ini

This Pr utilizes PlatformIO's feature of enabling caching to speed up compilation, and each time the code is changed, only the changed part is compiled, which can greatly speed up development and verification.
Debug compilation time：
First time:
After enabling caching:
We can see that after enabling caching, except for the first time which takes a long time, subsequent compilations are very fast

Enable caching to accelerate compilation

---

src/sensors/softfusion/softfusionsensor.h

Fix some microcontrollers crashing (Soft WDT reset) during the calibration loop

Fix softfusion watchdog timer reset

---

src/serial/serialcommands.cpp

People are confusing "PASS" with meaning that the WiFi passes something somehow, I think "PASSWD" should be more obvious, or maybe we should just say "PASSWORD"? We're not really limited on space here.

Change "PASS" to "PASSWD"

---

src/sensors/softfusion/drivers/bmi270.h

Both `i` and `bytes_to_read` are `size_t`, which are `unsigned long`. `i - bytes_to_read` always underflows and should have been `bytes_to_read - i` for how many bytes are left in the buffer. But since we're dealing with unsigned values, it's safer to only do additions and comparisons.

Fix bounds checks in BMI270 driver in `bulk_read`

---

src/sensors/softfusion/drivers/bmi270.h

Previously, required_length was always 0 because we shifting by a huge number, rather than the bit position. So the check for incomplete frames would never trigger. The final data frame in a FIFO read is sometimes an incomplete frame, and therefore we would read garbage for the data frame. There are often incomplete frames when we call LEDManager to blink the LED, because the FIFO overruns.
1. During gyroscope calibration, we often read random gyroscope samples, which throws off the calibration results.
2. During 6-sided accelerometer calibration, we often read random acceleration samples which causes rest detection to move on to collecting the next side, even if we don't move the tracker.
3. During normal operation, we will rarely read random gyroscope and accelerometer samples. These …

[BMI270] Fix bug in data frame size calculation

---

src/sensors/softfusion/drivers/bmi270.h
src/sensors/softfusion/softfusionsensor.h

On a normal reset, we set the CRT (motionless) registers at startup, and then apply the calibrated gryo offset to every gyro sample.
Previously, we performed gyro offset calibration before CRT calibration. This means that we are actually calculating the gyro offset based on a CRT of 0, instead of the actual CRT.
This change performs CRT calibration before gyro calibration, so that the gryo offset is based on the actual CRT.
Cherry-picked from:
https://github.com/l0ud/SlimeVR-Tracker-ESP-BMI270/commit/2424b2ff08197c6b2d236714d8ca6de929c6bbe9
https://github.com/l0ud/SlimeVR-Tracker-ESP-BMI270/commit/cf349886c1e1bf562ea033df31ec04e52e83358f

[sfusion, BMI270] Perform gryo motionless calibration before gyro offset calibration

---

.github/CODEOWNERS
src/consts.h
src/defines.h
src/sensors/SensorManager.cpp
src/sensors/SensorManager.h
src/sensors/bmi160sensor.h
src/sensors/bno055sensor.h
src/sensors/bno080sensor.h
src/sensors/icm20948sensor.h
src/sensors/mpu6050sensor.h
src/sensors/mpu9250sensor.h
src/sensors/sensoraddresses.h
src/sensors/softfusion/softfusionsensor.h
src/serial/serialcommands.cpp

Reverses IMU address change in defines.h introduced in #322.
The change is reversed for compatibility with web flasher, as well as for future expandability with use cases with more than 2 IMUs. Directly inputing the addresses give flexibility in case any address shifters are involved, or IMUs are wired in different configurations.

Reverse IMU I2C address from supplement to full

---

lib/i2cscan/i2cscan.cpp
lib/i2cscan/i2cscan.h
src/main.cpp
src/sensors/SensorManager.cpp

Makes I2Cscan non-blocking, resolves #377. I could only test it with one IMU on ESP8266, where it still connected to wifi even when the IMU was not present at all, or on other pins/address. Needs further testing.

Make I2Cscan non-blocking

---

src/network/connection.cpp
src/network/connection.h
src/sensors/RestCalibrationDetector.cpp
src/sensors/RestCalibrationDetector.h
src/sensors/bmi160sensor.cpp
src/sensors/bmi160sensor.h
src/sensors/bno055sensor.cpp
src/sensors/bno080sensor.cpp
src/sensors/sensor.cpp
src/sensors/sensor.h
src/sensors/softfusion/softfusionsensor.h

Adds rest calibration detection to the sensors, where it's possible to fetch this information in some shape or form, and includes it in the sensor info packet.
Solves #383

Report rest calibration

---

src/network/connection.cpp
src/sensors/sensor.h

Sensor rest calibration ack needs to support old server versions, this PR checks the packet length first, acks by default if not returned, and fixes the packet ack byte index. Also C++ does not initialize the boolean to false, so this sets it to false by default.
Fixes #388.

Ignore rest calibration ack if packet is too short

---

src/sensorinterface/I2CWireSensorInterface.cpp
src/sensors/softfusion/softfusionsensor.h

A couple of small issues left over from the runtime calibration merge.
The gpio_set_direction lines were originally called on a zero initialized value, which meant that pin 0 was always set to input.
Ticking calibrator twice probably doesn't cause huge issues, but I removed the second call just in case.

Small fixes

---

src/network/connection.cpp

This PR is to go with https://github.com/SlimeVR/SlimeVR-Server/pull/1317
From firmware v0.5.3 to v0.5.4, the SensorInfo packet has the rest calibration byte before the default position and data type, we should probably retain compatibility with the already released firmware and follow that packet order, otherwise we will be introducing some version-specific issues.

Re-order SensorInfo packet

---

src/sensors/softfusion/drivers/icm45base.h

we were using the 4 lowest gyro bits for the LSB bits of the accel, instead of the 4 lowest accel bits lol oopsie

ICM45*: Process accel sample LSB correctly

---

src/consts.h
src/network/connection.cpp
src/network/connection.h
src/network/packets.h
src/sensors/softfusion/drivers/icm45base.h

This PR aims to make changing packet code less error prone by introducing structs that describe most packets used for communication. Since communication is done using big endian data, steps are also taken, so that this is more or less automatically handled as well.
The only packets that didn't get turned into structs are the heartbeat packet (since it's empty, and 0 byte structs aren't supported by C++), the feature flags packet (since its length is complicated) and the handshake or tracker discovery packet (since this has a variable length string inside it).
The PR also cleans up some of the code surrounding these changes, for example by creating enum classes for the various packet values.

Refactor network packets into structs

---

src/sensors/SensorManager.cpp

This commit fixes the use case BNO08x whit out a interrupt pin.
This fix reflects the behavior till now where <uint8_t>255 was no int pin.

add handling for not given pin (-1 or 255)

---

src/sensors/bno080sensor.cpp

The BNO08x Sensor did not change its state when a i2c timeout is occurred, like losing connection to the extension.

Fix BNO SensorState when i2c disconnects while working

---

src/sensors/SensorManager.h
src/sensors/softfusion/drivers/icm45base.h

This PR fixes 2 more issues with ICM45*: 
- SensorManager.h now scans for an IMU twice, since ICM45* [may not respond on the first I2C transaction](https://github.com/tdk-invn-oss/motion.mcu.icm45686.driver/blob/fb4275febca58596774cee0dc0654cdc058a640c/icm45686/imu/inv_imu_driver.c#L66C5-L69). No other IMUs have this issue, so the 2nd scan will never run and therefore have any effect on them.
- ICM45* will never fully empty the FIFO, instead leaving one packet at all times. Not sure why, but fully emptying it will eventually cause FIFO corruption. This might be documented in AN-000364, just like the first issue, but no one's found this document anywhere on the web yet.

More ICM45 fixes

---

lib/bno080/PinInterface.h
src/sensorinterface/I2CPCAInterface.cpp
src/sensorinterface/I2CPCAInterface.h
src/sensorinterface/I2CWireSensorInterface.h
src/sensorinterface/SensorInterface.h
src/sensorinterface/SensorInterfaceManager.h
src/sensors/SensorManager.cpp

This PR aims to simplify the code around sensor interface creation by generalizing it and pulling into a single manager class. This should make adding new sensor and pin interfaces only require adding a couple more lines instead of having to reimplement the caches from zero every time.

Implement SensorInterfaceManager

---

src/configuration/Configuration.cpp
src/configuration/Configuration.h
src/configuration/SensorConfig.cpp
src/configuration/SensorConfig.h
src/network/connection.cpp
src/network/connection.h
src/network/packets.h
src/sensors/SensorToggles.cpp
src/sensors/SensorToggles.h
src/sensors/bno080sensor.cpp
src/sensors/bno080sensor.h
src/sensors/sensor.cpp
src/sensors/sensor.h
src/sensors/softfusion/CalibrationBase.h
src/sensors/softfusion/SoftfusionCalibration.h
src/sensors/softfusion/runtimecalibration/RuntimeCalibration.h
src/sensors/softfusion/softfusionsensor.h

This PR refactors feature toggling (previously only used for the magnetometer) to be more generic and easily extensible. Alongside this change it also introduces toggles for softfusion calibration and temperature gradient calibration.
Seemingly works for the magnetometer on the BNO085, the rest would likely need server implementation.

Refactor feature toggling into a class

---

src/network/connection.cpp

After a reboot of the tracker the optional sensor did show up on the server too. This is because a sensor packet was sent from all sensors including empty and unknown. This should hopefully fix the issue.
It is a fast fix. It probably would be better to move all this check to sensor. If the sensor has a change, set a flag, and reset the flag if the function gets called.

fix SensorStateUpdate

---

src/sensors/softfusion/drivers/icm45base.h

1. At startup, we were receiving invalid samples from the IMU and passing it to VQF. This causes huge initial rotations and accelerations that takes time for VQF to eliminate.
Fix is to check the header to see if the data is present. Also had to add a check for invalid gyro samples even though it is present.
2. During play, the tracker would rarely go haywire and jump into a random position. I suspect this is caused by a stack overflow, which causes the tracker to panic. Combined with problem (1), whenever the tracker restarts, it would send huge rotations and accelerations to the server. This causes the jump.
Fix is to make the read_buffer static, so that it's reserved on the BSS segment instead of the stack. I noticed this because I was getting panics when I tried to increase the size …

[ICM45*] Fix processing bad samples and stack overflow panics

---

src/sensors/SensorBuilder.h

The rework during the SPI implementation left out a default value for a define, which causes incompatibility with the firmware tool. Adding this back fixes the issue.

Fix defines compatibility

---

lib/bno080/PinInterface.h
src/logging/Logger.h
src/sensorinterface/DirectPinInterface.h
src/sensorinterface/I2CPCAInterface.h
src/sensorinterface/I2CWireSensorInterface.h
src/sensorinterface/MCP23X17PinInterface.h
src/sensorinterface/SensorInterface.h
src/sensors/SensorBuilder.h
src/sensors/softfusion/softfusionsensor.h
src/serial/serialcommands.cpp

I noticed that when the tracker serial console was reporting garbage data for the imu interface, because an std::string was passed to a %s format parameter expecing a cstring. I fixed this up and also added the format attribute to the logging methods, which tells gcc (and clang) that they are using the printf style format strings as params. Also fixed up any other warnings generated by this.

Tostring fix

---

src/sensors/softfusion/drivers/bmi160.h
src/sensors/softfusion/drivers/lsm6ds3trc.h
src/sensors/softfusion/softfusionsensor.h

This PR adds the functionality of allowing multiple WHOAMI values per SoftFusion sensor. It is mainly for parity with the old BMI160 driver, which handled revision 3 chips properly (those have a value of 0xD3), but it also allows LSM6DS3 to work with the LSM6DS3TR-C driver.

Allow multiple WHOAMI values per SoftFusion sensor

---

lib/i2cscan/i2cscan.cpp
src/batterymonitor.cpp
src/main.cpp
src/sensorinterface/I2CPCAInterface.cpp
src/sensorinterface/I2CWireSensorInterface.cpp
src/sensorinterface/SensorInterface.h
src/sensors/ADCResistanceSensor.cpp
src/sensors/SensorBuilder.h
src/sensors/SensorFusion.h
src/sensors/SensorFusionDMP.h
src/serial/serialcommands.cpp

make all esp32 define the same
only check if ESP32 is defined. The value changed from "1" to "ESP32" in pioarduino and tasmota in newer versions.
update esp32 to tasmota version

Esp32 fix defines

---

src/debug.h
src/globals.h
src/sensors/softfusion/drivers/icm45686.h

Allows user to easily disable external IMU clock, if they are using a design which doesn't have one

Add IMU_USE_EXTERNAL_CLOCK to debug.h

---

lib/vqf/vqf.h
src/sensors/softfusion/drivers/bmi160.h
src/sensors/softfusion/drivers/bmi270.h
src/sensors/softfusion/drivers/icm42688.h
src/sensors/softfusion/drivers/icm45605.h
src/sensors/softfusion/drivers/icm45686.h
src/sensors/softfusion/drivers/icm45base.h
src/sensors/softfusion/drivers/lsm6ds3trc.h
src/sensors/softfusion/drivers/lsm6dso.h
src/sensors/softfusion/drivers/lsm6dsr.h
src/sensors/softfusion/drivers/lsm6dsv.h
src/sensors/softfusion/drivers/mpu6050.h
src/sensors/softfusion/runtimecalibration/RuntimeCalibration.h

This PR:
- Applies the 2nd iteration of optimized VQFParams to every SoftFusion sensor
- Reduces the gyro ODR to 200Hz for all SoftFusion sensors
- Unifies accelerometer full-scale range for all SoftFusion sensors (it was 8G on some sensors before this, now it'll be 4G (except for maybe MPU6050 that sensor can go die))
- Makes sensor timestep calibration always trigger on boot

Optimized VQFParams 2: Electric Boogaloo
